version: '3.8'

services:
  app:
    build:
      context: .  # Context for building the Docker image
      dockerfile: Dockerfile  # Specify the Dockerfile to use
    volumes:
      - .:/app  # Bind mount the current directory to the app's working directory
    ports:
      - '5000:5000'  # Ensure this matches your app's listening port
    environment:
      NODE_ENV: development
      DB_HOST: db  # Service name of the PostgreSQL container
      DB_PORT: 5432  # Port PostgreSQL listens on inside the container
      DB_USER: george2  # PostgreSQL username
      DB_PASSWORD: 123456  # PostgreSQL password
      DB_NAME: ovarc  # PostgreSQL database name
    depends_on:
      - db  # Ensure db service starts before app

  db:
    image: postgres:13  # Use the official PostgreSQL image
    restart: always  # Restart policy for the PostgreSQL service
    environment:
      POSTGRES_USER: george2  # PostgreSQL username
      POSTGRES_PASSWORD: 123456  # PostgreSQL password
      POSTGRES_DB: ovarc  # Database name to create
    ports:
      - '5433:5432'  # Expose the PostgreSQL port on host port 5433
    volumes:
      - db_data:/var/lib/postgresql/data  # Persist database data

volumes:
  db_data:  # Named volume for PostgreSQL data
